routes/web.php
<?php

use App\Http\Controllers\Admin\OpensurveyController;
use App\Http\Controllers\Admin\SatkerController;
use App\Http\Controllers\Admin\PertanyaanController;
use App\Http\Controllers\Admin\PenggunaController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.login');
})->name('login');

// Route::get('/login', function () {
//     return view('pages.login');
// });

Route::get('/survey/{satker}/{name_responden}/{unique_kunjungan}', 'App\Http\Controllers\SurveyController@surveyWithName');
Route::get('/survey-satker/{satker}', 'App\Http\Controllers\SurveyController@surveySatker');
Route::get('/survey', 'App\Http\Controllers\SurveyController@index');
Route::post('/survey/simpan', 'App\Http\Controllers\SurveyController@saveAnswer');
Route::post('/survey/mulai', 'App\Http\Controllers\SurveyController@mulai');

Route::get('/admin', function () {
    return view('pages.login');
});

Route::get('/admin/register', function () {
    return view('pages.register');
});



// Route::get('/admin/pertanyaan', 'PertanyaanController@index');


// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', 'App\Http\Controllers\Admin\DashboardController@index' )->name('dashboard');

Route::group(['prefix' => 'admin','as'=>'admin.','middleware' =>['auth:sanctum', 'verified']],
function(){
    Route::resource('satker',SatkerController::class);

});

Route::group(['prefix' => 'admin','as'=>'admin.','middleware' =>['auth:sanctum', 'verified']],
function(){
    Route::resource('pertanyaan',PertanyaanController::class);

    Route::get('hasilsurvey', 'App\Http\Controllers\Admin\ReportController@hasilsurvey');
    Route::get('exporthasilsurvey', 'App\Http\Controllers\Admin\ReportController@exporthasilsurvey');
    Route::get('hasilsurveysatker', 'App\Http\Controllers\Admin\ReportController@hasilsurveysatker');
    Route::get('hasilsurveypersonal/{id_satker}', 'App\Http\Controllers\Admin\ReportController@hasilsurveypersonal');
    Route::post('hasilsurveysatkerdetail', 'App\Http\Controllers\Admin\ReportController@hasilsurveysatkerdetail')->name('hasilsurveysatkerdetail');
    Route::resource('opensurvey',OpensurveyController::class);
    Route::get('opensurvey/detail/{id}',[App\Http\Controllers\Admin\OpensurveyController::class, 'detail']);
    Route::put('opensurvey/detail/{id}',[App\Http\Controllers\Admin\OpensurveyController::class, 'ubahblok']);
    Route::post('opensurvey/detail',[App\Http\Controllers\Admin\OpensurveyController::class, 'simpanblok']);
    Route::post('opensurvey/pertanyaan',[App\Http\Controllers\Admin\OpensurveyController::class, 'simpanpertanyaan']);
    Route::delete('opensurvey/detail/{id}',[App\Http\Controllers\Admin\OpensurveyController::class, 'hapusblok']);
    Route::get('opensurvey/detail/table/{id_survey_blok}',[App\Http\Controllers\Admin\OpensurveyController::class, 'api_pertanyaan']);
    Route::get('opensurvey/detail/get/{id_survey_blok}',[App\Http\Controllers\Admin\OpensurveyController::class, 'get_pertanyaan']);
});

Route::group(['prefix' => 'admin','as'=>'admin.','middleware' =>['auth:sanctum', 'verified']],
function(){
    Route::resource('pengguna',PenggunaController::class);

});

// Route::get('/dashboard/pengguna', 'App\Http\Controllers\Admin\PenggunaController@index');
// Route::get('/dashboard/{name}/edit', 'App\Http\Controllers\Admin\PenggunaController@edit');
// Route::put('/dashboard/{name}', 'App\Http\Controllers\Admin\PenggunaController@update');
// Route::delete('/dashboard/{name}', 'App\Http\Controllers\Admin\PenggunaController@delete');

app/Models/Pertanyaans.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pertanyaans extends Model
{
    use HasFactory;
    public $table = 'pertanyaans';

    protected $dates = [
        'updated_at',
        'created_at',
        'deleted_at',
    ];

    protected $fillable = [
        //'id',
        'urutan',
        'pertanyaan',
        'updated_at',
        'created_at',
        'deleted_at',
    ];
}

app/Http/Controllers/Admin/PertanyaanController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Pertanyaans;
use Illuminate\Support\Facades\DB;

class PertanyaanController extends Controller
{
    //
    

    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {   //$datapertanyaan = DB::table('pertanyaans')->get();
         $datapertanyaan = Pertanyaans::all();    
        // $datasatker = DB::table('satkers as s1')
        // ->join('satkers as s2','s2.id','=','s1.parent_satker')
        // ->select('s1.id as id','s1.nama_satker as nama_satker', 's2.nama_satker as parent_satker', 's1.tipe_satker as tipe_satker')
        // ->get();
        return view('pages.admin.pertanyaan.index', compact('datapertanyaan'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //return view('pages.admin.pertanyaan.create');
        $datapertanyaan = Pertanyaans::all();
        return view('pages.admin.pertanyaan.create', compact('datapertanyaan'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        

        $this->validate($request,[
    		'urutan' => 'required',
    		'pertanyaan' => 'required'
    	]);
 
        $data = $request->all();
        $service = Pertanyaans::create($data);
 
        toast()->success('Berhasil Menyimpan Data');
    	return redirect('/admin/pertanyaan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {   
        // $datapertanyaan = Pertanyaans::where($id)->first();
        $datapertanyaan = Pertanyaans::find($id);
        // $datasatker = DB::table('satkers as s1')
        // ->join('satkers as s2','s2.id','=','s1.parent_satker')
        // ->select('s1.id as id','s1.nama_satker as nama_satker', 's2.nama_satker as parent_satker', 's1.tipe_satker as tipe_satker')
        // ->where('s1.id', $id)
        // ->first();

        return view('pages.admin.pertanyaan.show', compact('datapertanyaan'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {   $datapertanyaan = Pertanyaans::find($id);
        return view('pages.admin.pertanyaan.edit', compact('datapertanyaan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
    		'urutan' => 'required'
    	]);
        Pertanyaans::where('id', $id)
            ->update([
                'urutan' => $request["urutan"],
                'pertanyaan' => $request["pertanyaan"],
            ]);

        toast()->success('Berhasil Mengubah Data');
    	return redirect('/admin/pertanyaan');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        {
            $datapertanyaan = Pertanyaans::find($id);
            $datapertanyaan->delete();
            toast()->success('Berhasil Menghapus Data');
            return redirect('/admin/pertanyaan');
        }
    }
}

resources/views/pages/admin/pertanyaan/create.blade.php
@extends('layouts.admin')

@section('title', ' Pertanyaan ')

@section('content')
@section('breadcrumb', ' Tambah Pertanyaan ')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-icon" data-background-color="purple">
                            <i class="material-icons">assignment</i>
                        </div>
                        <form action="{{ route('admin.pertanyaan.store') }}" method="POST">
                            @csrf
                            <div class="card-content">
                                <h4 class="card-title">Tambah Pertanyaan</h4>
                                <div class="form-group label-floating">
                                    <label class="control-label">
                                        Nomor Urutan
                                        <small>*</small>
                                    </label>
                                    <input class="form-control" name="urutan" required="true" />
                                    @error('urutan')
                                        <div class="alert alert-danger">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group label-floating">
                                    <label class="control-label">
                                        Pertanyaan
                                        <small>*</small>
                                    </label>
                                    <input class="form-control" name="pertanyaan" required="true" />
                                    @error('pertanyaan')
                                        <div class="alert alert-danger">
                                            {{ $message }}
                                        </div>
                                    @enderror                      
                                </div>
                                <div class="category form-category">
                                    <small>*</small> Harus Diisi</div>
                                <div class="form-footer text-right">
                                    <div class="checkbox pull-left">
                                        <label>
                                            <input type="checkbox" name="optionsCheckboxes"> Saya yakin menyimpan data ini
                                        </label>
                                    </div>
                                    <a href="{{ route('admin.pertanyaan.index') }}" class="btn btn-danger btn-fill">Kembali</a>
                                    <button type="submit" class="btn btn-primary btn-fill">Simpan</button>
                                </div>
                            </div>
                        </form>
                        <!-- end content-->
                    </div>
                    <!--  end card  -->
                </div>
                <!-- end col-md-12 -->
            </div>
            <!-- end row -->
        </div>
    </div>
    

@endsection

@push('after-script')

<script src="{{ asset('/assets/js/jquery.datatables.js') }}"></script>
<!-- Sweet Alert 2 plugin -->
<script src="{{ asset('/assets/js/sweetalert2.js') }}"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $('#datatables').DataTable({
            "pagingType": "full_numbers",
            "lengthMenu": [
                [10, 25, 50, -1],
                [10, 25, 50, "All"]
            ],
            responsive: true,
            language: {
                search: "_INPUT_",
                searchPlaceholder: "Search records",
            }

        });


        var table = $('#datatables').DataTable();

        // Edit record
        table.on('click', '.edit', function() {
            $tr = $(this).closest('tr');

            var data = table.row($tr).data();
            alert('You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.');
        });

        // Delete a record
        table.on('click', '.remove', function(e) {
            $tr = $(this).closest('tr');
            table.row($tr).remove().draw();
            e.preventDefault();
        });

        //Like record
        table.on('click', '.like', function() {
            alert('You clicked on Like button');
        });

        $('.card .material-datatables label').addClass('form-group');
    });
</script>
    
@endpush

resources/views/pages/admin/pertanyaan/edit.blade.php
@extends('layouts.admin')

@section('title', ' Pertanyaan ')

@section('content')
@section('breadcrumb', ' Tambah Pertanyaan ')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-icon" data-background-color="purple">
                            <i class="material-icons">assignment</i>
                        </div>
                        <form action="{{ route('admin.pertanyaan.update', $datapertanyaan->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="card-content">
                                <h4 class="card-title">Edit Pertanyaan</h4>
                                <div class="form-group label-floating">
                                    <label class="control-label">
                                        Urutan
                                        <small>*</small>
                                    </label>
                                    <input class="form-control" name="urutan" required="true" value="{{ $datapertanyaan->urutan }}" />
                                    @error('urutan')
                                        <div class="alert alert-danger">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group label-floating">
                                    <label class="control-label">
                                        Pertanyaan
                                        <small>*</small>
                                    </label>
                                    <input class="form-control" name="pertanyaan" required="true" value="{{ $datapertanyaan->pertanyaan }}"/>
                                    @error('pertanyaan')
                                        <div class="alert alert-danger">
                                            {{ $message }}
                                        </div>
                                    @enderror                      
                                </div>
                                
                                <div class="category form-category">
                                    <small>*</small> Harus Diisi</div>
                                <div class="form-footer text-right">
                                    <div class="checkbox pull-left">
                                        <label>
                                            <input type="checkbox" name="optionsCheckboxes"> Saya yakin mengubah data ini
                                        </label>
                                    </div>
                                    <a href="{{ route('admin.pertanyaan.index') }}" class="btn btn-danger btn-fill">Kembali</a>
                                    <button type="submit" class="btn btn-primary btn-fill">Simpan</button>
                                </div>
                            </div>
                        </form>
                        <!-- end content-->
                    </div>
                    <!--  end card  -->
                </div>
                <!-- end col-md-12 -->
            </div>
            <!-- end row -->
        </div>
    </div>
    

@endsection

@push('after-script')

<script src="{{ asset('/assets/js/jquery.datatables.js') }}"></script>
<!-- Sweet Alert 2 plugin -->
<script src="{{ asset('/assets/js/sweetalert2.js') }}"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $('#datatables').DataTable({
            "pagingType": "full_numbers",
            "lengthMenu": [
                [10, 25, 50, -1],
                [10, 25, 50, "All"]
            ],
            responsive: true,
            language: {
                search: "_INPUT_",
                searchPlaceholder: "Search records",
            }

        });


        var table = $('#datatables').DataTable();

        // Edit record
        table.on('click', '.edit', function() {
            $tr = $(this).closest('tr');

            var data = table.row($tr).data();
            alert('You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.');
        });

        // Delete a record
        table.on('click', '.remove', function(e) {
            $tr = $(this).closest('tr');
            table.row($tr).remove().draw();
            e.preventDefault();
        });

        //Like record
        table.on('click', '.like', function() {
            alert('You clicked on Like button');
        });

        $('.card .material-datatables label').addClass('form-group');
    });
</script>
    
@endpush

resources/views/pages/admin/pertanyaan/index.blade.php
@extends('layouts.admin')

@section('title', 'pertanyaan ')

@section('content')
@section('breadcrumb', ' Pertanyaan ')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-icon" data-background-color="purple">
                            <i class="material-icons">assignment</i>
                        </div>
                        <div class="card-content">
                            <a href="{{ route('admin.pertanyaan.create')}}"> <button class="btn btn-primary" style="float: right;">Tambah</button></a>
                            <h4 class="card-title">Daftar Pertanyaan</h4>
                            <div class="material-datatables">
                                
                                <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                                    <thead>
                                        <tr>
                                            <th width="5%">No</th>
                                            <th>Pertanyaan</th>
                                            <th>Urutan</th>
                                            <th width="10%"class="disabled-sorting text-right">Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($datapertanyaan as $key => $datapertanyaan )
                                        <tr>
                                            
                                            <td>{{$key + 1}}</td>
                                            <td>{{ $datapertanyaan->pertanyaan }}</td>
                                            <td>{{ $datapertanyaan->urutan }}</td>
                                            <td class="td-actions text-right">
                                                <form action="{{ route('admin.pertanyaan.destroy', $datapertanyaan->id) }}" method="POST">
                                                    @csrf
                                                    @method('DELETE')
                                                    <a href="{{ route('admin.pertanyaan.show', $datapertanyaan->id) }}" type="button" rel="tooltip" class="btn btn-info btn-simple" data-original-title="" title="">
                                                        <i class="material-icons">list</i>
                                                    </a>
                                                    <a href="{{ route('admin.pertanyaan.edit', $datapertanyaan->id) }}" type="button" rel="tooltip" class="btn btn-success btn-simple" data-original-title="" title="">
                                                        <i class="material-icons">edit</i>
                                                    </a>
                                                    <button onclick="confirmationDelete()" type="submit" rel="tooltip" class="btn btn-danger btn-simple" data-original-title="" title="" >
                                                        <i class="material-icons">close</i>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                        @empty

                                        @endforelse
                                    </tbody>
                                    
                                </table>
                                
                                    
                                
                                
                            </div>
                        </div>
                        <!-- end content-->
                    </div>
                    <!--  end card  -->
                </div>
                <!-- end col-md-12 -->
            </div>
            <!-- end row -->
        </div>
    </div>
    

@endsection

@push('after-script')

<script src="{{ asset('/assets/js/jquery.datatables.js') }}"></script>
<!-- Sweet Alert 2 plugin -->
<script src="{{ asset('/assets/js/sweetalert2.js') }}"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $('#datatables').DataTable({
            "pagingType": "full_numbers",
            "lengthMenu": [
                [10, 25, 50, -1],
                [10, 25, 50, "All"]
            ],
            responsive: true,
            language: {
                search: "_INPUT_",
                searchPlaceholder: "Search records",
            }

        });


        var table = $('#datatables').DataTable();

        // Edit record
        table.on('click', '.edit', function() {
            $tr = $(this).closest('tr');

            var data = table.row($tr).data();
            alert('You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.');
        });

        // Delete a record
        table.on('click', '.remove', function(e) {
            $tr = $(this).closest('tr');
            table.row($tr).remove().draw();
            e.preventDefault();
        });

        //Like record
        table.on('click', '.like', function() {
            alert('You clicked on Like button');
        });

        $('.card .material-datatables label').addClass('form-group');
    });

    function confirmationDelete() {
    confirm("Apakah anda yakin untuk menghapus")
    }
</script>
    
@endpush

resources/views/pages/admin/pertanyaan/show.blade.php
@extends('layouts.admin')

@section('title', ' Pertanyaan ')

@section('content')
@section('breadcrumb', ' Detail Pertanyaan ')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-icon" data-background-color="purple">
                            <i class="material-icons">assignment</i>
                        </div>
                        @csrf
                        <div class="card-content">
                            <h4 class="card-title">Detail Pertanyaan</h4>
                            <div class="form-group label-floating">
                                <label class="control-label">
                                    No Urutan
                                    <small>*</small>
                                </label>
                                <input class="form-control" name="urutan" required="true" disabled value="{{ $datapertanyaan->urutan }}" />
                                @error('nama_satker')
                                    <div class="alert alert-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                            <div class="form-group label-floating">
                                    <label class="control-label">
                                        Pertanyaan
                                        <small>*</small>
                                    </label>
                                    <input class="form-control" name="pertanyaan" required="true" disabled value="{{ $datapertanyaan->pertanyaan }}"/>
                                    @error('pertanyaan')
                                        <div class="alert alert-danger">
                                            {{ $message }}
                                        </div>
                                    @enderror                      
                            </div>
                        
                            {{-- <div class="category form-category">
                                <small>*</small> Harus Diisi
                            </div> --}}
                            <div class="form-footer text-right">
                                {{-- <div class="checkbox pull-left">
                                    <label>
                                        <input type="checkbox" name="optionsCheckboxes"> Saya yakin menyimpan data ini
                                    </label>
                                </div> --}}
                                <a href="{{ route('admin.pertanyaan.index') }}" class="btn btn-danger btn-fill">Kembali</a>
                            </div>
                        </div>
                        <!-- end content-->
                    </div>
                    <!--  end card  -->
                </div>
                <!-- end col-md-12 -->
            </div>
            <!-- end row -->
        </div>
    </div>
    

@endsection

@push('after-script')

<script src="{{ asset('/assets/js/jquery.datatables.js') }}"></script>
<!-- Sweet Alert 2 plugin -->
<script src="{{ asset('/assets/js/sweetalert2.js') }}"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $('#datatables').DataTable({
            "pagingType": "full_numbers",
            "lengthMenu": [
                [10, 25, 50, -1],
                [10, 25, 50, "All"]
            ],
            responsive: true,
            language: {
                search: "_INPUT_",
                searchPlaceholder: "Search records",
            }

        });


        var table = $('#datatables').DataTable();

        // Edit record
        table.on('click', '.edit', function() {
            $tr = $(this).closest('tr');

            var data = table.row($tr).data();
            alert('You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.');
        });

        // Delete a record
        table.on('click', '.remove', function(e) {
            $tr = $(this).closest('tr');
            table.row($tr).remove().draw();
            e.preventDefault();
        });

        //Like record
        table.on('click', '.like', function() {
            alert('You clicked on Like button');
        });

        $('.card .material-datatables label').addClass('form-group');
    });
</script>
    
@endpush