routes/web.php
<?php

use App\Http\Controllers\Admin\OpensurveyController;
use App\Http\Controllers\Admin\SatkerController;
use App\Http\Controllers\Admin\PertanyaanController;
use App\Http\Controllers\Admin\PenggunaController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.login');
})->name('login');

// Route::get('/login', function () {
//     return view('pages.login');
// });

Route::get('/survey/{satker}/{name_responden}/{unique_kunjungan}', 'App\Http\Controllers\SurveyController@surveyWithName');
Route::get('/survey-satker/{satker}', 'App\Http\Controllers\SurveyController@surveySatker');
Route::get('/survey', 'App\Http\Controllers\SurveyController@index');
Route::post('/survey/simpan', 'App\Http\Controllers\SurveyController@saveAnswer');
Route::post('/survey/mulai', 'App\Http\Controllers\SurveyController@mulai');

Route::get('/admin', function () {
    return view('pages.login');
});

Route::get('/admin/register', function () {
    return view('pages.register');
});



// Route::get('/admin/pertanyaan', 'PertanyaanController@index');


// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', 'App\Http\Controllers\Admin\DashboardController@index' )->name('dashboard');

Route::group(['prefix' => 'admin','as'=>'admin.','middleware' =>['auth:sanctum', 'verified']],
function(){
    Route::resource('satker',SatkerController::class);

});

Route::group(['prefix' => 'admin','as'=>'admin.','middleware' =>['auth:sanctum', 'verified']],
function(){
    Route::resource('pertanyaan',PertanyaanController::class);

    Route::get('hasilsurvey', 'App\Http\Controllers\Admin\ReportController@hasilsurvey');
    Route::get('exporthasilsurvey', 'App\Http\Controllers\Admin\ReportController@exporthasilsurvey');
    Route::get('hasilsurveysatker', 'App\Http\Controllers\Admin\ReportController@hasilsurveysatker');
    Route::get('hasilsurveypersonal/{id_satker}', 'App\Http\Controllers\Admin\ReportController@hasilsurveypersonal');
    Route::post('hasilsurveysatkerdetail', 'App\Http\Controllers\Admin\ReportController@hasilsurveysatkerdetail')->name('hasilsurveysatkerdetail');
    Route::resource('opensurvey',OpensurveyController::class);
    Route::get('opensurvey/detail/{id}',[App\Http\Controllers\Admin\OpensurveyController::class, 'detail']);
    Route::put('opensurvey/detail/{id}',[App\Http\Controllers\Admin\OpensurveyController::class, 'ubahblok']);
    Route::post('opensurvey/detail',[App\Http\Controllers\Admin\OpensurveyController::class, 'simpanblok']);
    Route::post('opensurvey/pertanyaan',[App\Http\Controllers\Admin\OpensurveyController::class, 'simpanpertanyaan']);
    Route::delete('opensurvey/detail/{id}',[App\Http\Controllers\Admin\OpensurveyController::class, 'hapusblok']);
    Route::get('opensurvey/detail/table/{id_survey_blok}',[App\Http\Controllers\Admin\OpensurveyController::class, 'api_pertanyaan']);
    Route::get('opensurvey/detail/get/{id_survey_blok}',[App\Http\Controllers\Admin\OpensurveyController::class, 'get_pertanyaan']);
});

Route::group(['prefix' => 'admin','as'=>'admin.','middleware' =>['auth:sanctum', 'verified']],
function(){
    Route::resource('pengguna',PenggunaController::class);

});

// Route::get('/dashboard/pengguna', 'App\Http\Controllers\Admin\PenggunaController@index');
// Route::get('/dashboard/{name}/edit', 'App\Http\Controllers\Admin\PenggunaController@edit');
// Route::put('/dashboard/{name}', 'App\Http\Controllers\Admin\PenggunaController@update');
// Route::delete('/dashboard/{name}', 'App\Http\Controllers\Admin\PenggunaController@delete');

app/Models/Satkers.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class Satkers extends Model
{

    public $table = 'satkers';

    protected $dates = [
        'updated_at',
        'created_at',
        'deleted_at',
    ];

    protected $fillable = [
        'id',
        'parent_satker',
        'nama_satker',
        'tipe_satker',
        'updated_at',
        'created_at',
        'deleted_at',
    ];


    public function parent_satkers()

    {
        return $this->belongsTo('App\Models\Satkers','id','parent_satker');
    }
    
}

app/Http/Controllers/Admin/SatkerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Satkers;
use Illuminate\Support\Facades\DB;

class SatkerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $datasatker = DB::table('satkers as s1')
        ->join('satkers as s2','s2.id','=','s1.parent_satker')
        ->select('s1.id as id','s1.nama_satker as nama_satker', 's2.nama_satker as parent_satker', 's1.tipe_satker as tipe_satker')
        ->get();
        return view('pages.admin.satker.index', compact('datasatker'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $datasatker = Satkers::all();
        return view('pages.admin.satker.create', compact('datasatker'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        

        $this->validate($request,[
    		'nama_satker' => 'required',
    		'parent_satker' => 'required',
            'tipe_satker' => 'required',
    	]);
 
        $data = $request->all();
        $service = Satkers::create($data);
 
        toast()->success('Berhasil Menyimpan Data');
    	return redirect('/admin/satker');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $datasatker = DB::table('satkers as s1')
        ->join('satkers as s2','s2.id','=','s1.parent_satker')
        ->select('s1.id as id','s1.nama_satker as nama_satker', 's2.nama_satker as parent_satker', 's1.tipe_satker as tipe_satker')
        ->where('s1.id', $id)
        ->first();

        return view('pages.admin.satker.show', compact('datasatker'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $datasatker = DB::table('satkers as s1')
        ->join('satkers as s2','s2.id','=','s1.parent_satker')
        ->select('s1.id as id','s1.nama_satker as nama_satker', 's2.id as id_parent_satker', 's2.nama_satker as parent_satker', 's1.tipe_satker as tipe_satker')
        ->where('s1.id', $id)
        ->first();

        $datasatker2 = DB::table('satkers as s1')
        ->join('satkers as s2','s2.id','=','s1.parent_satker')
        ->select('s1.id as id','s1.nama_satker as nama_satker', 's2.id as id_parent_satker', 's2.nama_satker as parent_satker', 's1.tipe_satker as tipe_satker')
        ->get();

        return view('pages.admin.satker.edit', compact('datasatker','datasatker2'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Satkers::where('id', $id)
            ->update([
                'nama_satker' => $request["nama_satker"],
                'parent_satker' => $request["parent_satker"],
                'tipe_satker' => $request["tipe_satker"],
            ]);

        toast()->success('Berhasil Mengubah Data');
    	return redirect('/admin/satker');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        {
            $datasatker = Satkers::find($id);
            $datasatker->delete();
            toast()->success('Berhasil Menghapus Data');
            return redirect('/admin/satker');
        }
    }
}

resources/views/pages/admin/satker/create.blade.php
@extends('layouts.admin')

@section('title', ' Satker ')

@section('content')
@section('breadcrumb', ' Tambah Satker ')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-icon" data-background-color="purple">
                            <i class="material-icons">assignment</i>
                        </div>
                        <form action="{{ route('admin.satker.store') }}" method="POST">
                            @csrf
                            <div class="card-content">
                                <h4 class="card-title">Tambah Satker</h4>
                                <div class="form-group label-floating">
                                    <label class="control-label">
                                        Nama Satker
                                        <small>*</small>
                                    </label>
                                    <input class="form-control" name="nama_satker" required="true" />
                                    @error('nama_satker')
                                        <div class="alert alert-danger">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group label-floating">
                                    <label class="control-label">
                                        Parent Satker
                                        <small>*</small>
                                    </label>
                                    <select name="parent_satker" id="parent_satker" class="form-control"> 
                                        <option value="">== PILIH PARENT ==</option>    
                                        @foreach ($datasatker as $data )
                                        <option value="{{ $data->id }}">{{ $data->nama_satker }}</option>    
                                        @endforeach 
                                    </select>      
                                    @error('parent_satker')
                                        <div class="alert alert-danger">
                                            {{ $message }}
                                        </div>
                                    @enderror              
                                </div>
                                <div class="form-group label-floating">
                                    <label class="control-label">
                                        Tipe Satker
                                        <small>*</small>
                                    </label>
                                    <select name="tipe_satker" id="tipe_satker" class="form-control">
                                        <option value="">== PILIH TIPE ==</option>
                                        <option value="1">PUSAT</option>
                                        <option value="2">PROVINSI</option>
                                        <option value="3">KAB/KOTA</option>
                                    </select> 
                                    @error('tipe_satker')
                                        <div class="alert alert-danger">
                                            {{ $message }}
                                        </div>
                                    @enderror                                 
                                </div>
                                <div class="category form-category">
                                    <small>*</small> Harus Diisi</div>
                                <div class="form-footer text-right">
                                    <div class="checkbox pull-left">
                                        <label>
                                            <input type="checkbox" name="optionsCheckboxes"> Saya yakin menyimpan data ini
                                        </label>
                                    </div>
                                    <a href="{{ route('admin.satker.index') }}" class="btn btn-danger btn-fill">Kembali</a>
                                    <button type="submit" class="btn btn-primary btn-fill">Simpan</button>
                                </div>
                            </div>
                        </form>
                        <!-- end content-->
                    </div>
                    <!--  end card  -->
                </div>
                <!-- end col-md-12 -->
            </div>
            <!-- end row -->
        </div>
    </div>
    

@endsection

@push('after-script')

<script src="{{ asset('/assets/js/jquery.datatables.js') }}"></script>
<!-- Sweet Alert 2 plugin -->
<script src="{{ asset('/assets/js/sweetalert2.js') }}"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $('#datatables').DataTable({
            "pagingType": "full_numbers",
            "lengthMenu": [
                [10, 25, 50, -1],
                [10, 25, 50, "All"]
            ],
            responsive: true,
            language: {
                search: "_INPUT_",
                searchPlaceholder: "Search records",
            }

        });


        var table = $('#datatables').DataTable();

        // Edit record
        table.on('click', '.edit', function() {
            $tr = $(this).closest('tr');

            var data = table.row($tr).data();
            alert('You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.');
        });

        // Delete a record
        table.on('click', '.remove', function(e) {
            $tr = $(this).closest('tr');
            table.row($tr).remove().draw();
            e.preventDefault();
        });

        //Like record
        table.on('click', '.like', function() {
            alert('You clicked on Like button');
        });

        $('.card .material-datatables label').addClass('form-group');
    });
</script>
    
@endpush

resources/views/pages/admin/satker/edit.blade.php
@extends('layouts.admin')

@section('title', ' Satker ')

@section('content')
@section('breadcrumb', ' Tambah Satker ')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-icon" data-background-color="purple">
                            <i class="material-icons">assignment</i>
                        </div>
                        <form action="{{ route('admin.satker.update', $datasatker->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="card-content">
                                <h4 class="card-title">Edit Satker</h4>
                                <div class="form-group label-floating">
                                    <label class="control-label">
                                        Nama Satker
                                        <small>*</small>
                                    </label>
                                    <input class="form-control" name="nama_satker" required="true" value="{{ $datasatker->nama_satker }}" />
                                    @error('nama_satker')
                                        <div class="alert alert-danger">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group label-floating">
                                    <label class="control-label">
                                        Parent Satker
                                        <small>*</small>
                                    </label>
                                    <select name="parent_satker" id="parent_satker" class="form-control"> 
                                        <option value="{{ $datasatker->id_parent_satker }}" >{{ $datasatker->parent_satker }}</option>  
                                        @foreach ($datasatker2 as $data )
                                        <option value="{{ $data->id }}">{{ $data->nama_satker }}</option>    
                                        @endforeach   
                                    </select>      
                                    @error('parent_satker')
                                        <div class="alert alert-danger">
                                            {{ $message }}
                                        </div>
                                    @enderror              
                                </div>
                                <div class="form-group label-floating">
                                    <label class="control-label">
                                        Tipe Satker
                                        <small>*</small>
                                    </label>
                                    <select name="tipe_satker" id="tipe_satker" class="form-control">
                                        <option value="{{ $datasatker->tipe_satker }}">@if($datasatker->tipe_satker == "1") PUSAT
                                            @elseif($datasatker->tipe_satker == "2") PROVINSI
                                            @else KAB/KOTA
                                            @endif</option>
                                            <option value="1">PUSAT</option>
                                            <option value="2">PROVINSI</option>
                                            <option value="3">KAB/KOTA</option>
                                    </select> 
                                    @error('tipe_satker')
                                        <div class="alert alert-danger">
                                            {{ $message }}
                                        </div>
                                    @enderror                                 
                                </div>
                                <div class="category form-category">
                                    <small>*</small> Harus Diisi</div>
                                <div class="form-footer text-right">
                                    <div class="checkbox pull-left">
                                        <label>
                                            <input type="checkbox" name="optionsCheckboxes"> Saya yakin mengubah data ini
                                        </label>
                                    </div>
                                    <a href="{{ route('admin.satker.index') }}" class="btn btn-danger btn-fill">Kembali</a>
                                    <button type="submit" class="btn btn-primary btn-fill">Simpan</button>
                                </div>
                            </div>
                        </form>
                        <!-- end content-->
                    </div>
                    <!--  end card  -->
                </div>
                <!-- end col-md-12 -->
            </div>
            <!-- end row -->
        </div>
    </div>
    

@endsection

@push('after-script')

<script src="{{ asset('/assets/js/jquery.datatables.js') }}"></script>
<!-- Sweet Alert 2 plugin -->
<script src="{{ asset('/assets/js/sweetalert2.js') }}"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $('#datatables').DataTable({
            "pagingType": "full_numbers",
            "lengthMenu": [
                [10, 25, 50, -1],
                [10, 25, 50, "All"]
            ],
            responsive: true,
            language: {
                search: "_INPUT_",
                searchPlaceholder: "Search records",
            }

        });


        var table = $('#datatables').DataTable();

        // Edit record
        table.on('click', '.edit', function() {
            $tr = $(this).closest('tr');

            var data = table.row($tr).data();
            alert('You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.');
        });

        // Delete a record
        table.on('click', '.remove', function(e) {
            $tr = $(this).closest('tr');
            table.row($tr).remove().draw();
            e.preventDefault();
        });

        //Like record
        table.on('click', '.like', function() {
            alert('You clicked on Like button');
        });

        $('.card .material-datatables label').addClass('form-group');
    });
</script>
    
@endpush

resources/views/pages/admin/satker/index.blade.php
@extends('layouts.admin')

@section('title', ' Satker ')

@section('content')
@section('breadcrumb', ' Satker ')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-icon" data-background-color="purple">
                            <i class="material-icons">assignment</i>
                        </div>
                        <div class="card-content">
                            <a href="{{ route('admin.satker.create')}}"> <button class="btn btn-primary" style="float: right;">Tambah</button></a>
                            <h4 class="card-title">Data Satker</h4>
                            <div class="material-datatables">
                                
                                <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                                    <thead>
                                        <tr>
                                            <th>No</th>
                                            <th>Nama Satker</th>
                                            <th>Parent Satker</th>
                                            <th>Tipe Satker</th>
                                            <th class="disabled-sorting text-right">Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($datasatker as $key => $datasatker )
                                        <tr>
                                            
                                            <td>{{$key + 1}}</td>
                                            <td>{{ $datasatker->nama_satker }}</td>
                                            <td>{{ $datasatker->parent_satker }}</td>
                                            <td>
                                            @if($datasatker->tipe_satker == "1") PUSAT
                                            @elseif($datasatker->tipe_satker == "2") PROVINSI
                                            @else KABUPATEN KOTA
                                            @endif
                                            </td>
                                            <td class="td-actions text-right">
                                                <form action="{{ route('admin.satker.destroy', $datasatker->id) }}" method="POST">
                                                    @csrf
                                                    @method('DELETE')
                                                    <a href="{{ route('admin.satker.show', $datasatker->id) }}" type="button" rel="tooltip" class="btn btn-info btn-simple" data-original-title="" title="">
                                                        <i class="material-icons">list</i>
                                                    </a>
                                                    <a href="{{ route('admin.satker.edit', $datasatker->id) }}" type="button" rel="tooltip" class="btn btn-success btn-simple" data-original-title="" title="">
                                                        <i class="material-icons">edit</i>
                                                    </a>
                                                    <button onclick="confirmationDelete()" type="submit" rel="tooltip" class="btn btn-danger btn-simple" data-original-title="" title="" >
                                                        <i class="material-icons">close</i>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                        @empty

                                        @endforelse
                                    </tbody>
                                    
                                </table>
                                
                                    
                                
                                
                            </div>
                        </div>
                        <!-- end content-->
                    </div>
                    <!--  end card  -->
                </div>
                <!-- end col-md-12 -->
            </div>
            <!-- end row -->
        </div>
    </div>
    

@endsection

@push('after-script')

<script src="{{ asset('/assets/js/jquery.datatables.js') }}"></script>
<!-- Sweet Alert 2 plugin -->
<script src="{{ asset('/assets/js/sweetalert2.js') }}"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $('#datatables').DataTable({
            "pagingType": "full_numbers",
            "lengthMenu": [
                [10, 25, 50, -1],
                [10, 25, 50, "All"]
            ],
            responsive: true,
            language: {
                search: "_INPUT_",
                searchPlaceholder: "Search records",
            }

        });


        var table = $('#datatables').DataTable();

        // Edit record
        table.on('click', '.edit', function() {
            $tr = $(this).closest('tr');

            var data = table.row($tr).data();
            alert('You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.');
        });

        // Delete a record
        table.on('click', '.remove', function(e) {
            $tr = $(this).closest('tr');
            table.row($tr).remove().draw();
            e.preventDefault();
        });

        //Like record
        table.on('click', '.like', function() {
            alert('You clicked on Like button');
        });

        $('.card .material-datatables label').addClass('form-group');
    });

    function confirmationDelete() {
    confirm("Apakah anda yakin untuk menghapus")
    }
</script>
    
@endpush