routes/web.php
<?php

use App\Http\Controllers\Admin\OpensurveyController;
use App\Http\Controllers\Admin\SatkerController;
use App\Http\Controllers\Admin\PertanyaanController;
use App\Http\Controllers\Admin\PenggunaController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.login');
})->name('login');

// Route::get('/login', function () {
//     return view('pages.login');
// });

Route::get('/survey/{satker}/{name_responden}/{unique_kunjungan}', 'App\Http\Controllers\SurveyController@surveyWithName');
Route::get('/survey-satker/{satker}', 'App\Http\Controllers\SurveyController@surveySatker');
Route::get('/survey', 'App\Http\Controllers\SurveyController@index');
Route::post('/survey/simpan', 'App\Http\Controllers\SurveyController@saveAnswer');
Route::post('/survey/mulai', 'App\Http\Controllers\SurveyController@mulai');

Route::get('/admin', function () {
    return view('pages.login');
});

Route::get('/admin/register', function () {
    return view('pages.register');
});



// Route::get('/admin/pertanyaan', 'PertanyaanController@index');


// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', 'App\Http\Controllers\Admin\DashboardController@index' )->name('dashboard');

Route::group(['prefix' => 'admin','as'=>'admin.','middleware' =>['auth:sanctum', 'verified']],
function(){
    Route::resource('satker',SatkerController::class);

});

Route::group(['prefix' => 'admin','as'=>'admin.','middleware' =>['auth:sanctum', 'verified']],
function(){
    Route::resource('pertanyaan',PertanyaanController::class);

    Route::get('hasilsurvey', 'App\Http\Controllers\Admin\ReportController@hasilsurvey');
    Route::get('exporthasilsurvey', 'App\Http\Controllers\Admin\ReportController@exporthasilsurvey');
    Route::get('hasilsurveysatker', 'App\Http\Controllers\Admin\ReportController@hasilsurveysatker');
    Route::get('hasilsurveypersonal/{id_satker}', 'App\Http\Controllers\Admin\ReportController@hasilsurveypersonal');
    Route::post('hasilsurveysatkerdetail', 'App\Http\Controllers\Admin\ReportController@hasilsurveysatkerdetail')->name('hasilsurveysatkerdetail');
    Route::resource('opensurvey',OpensurveyController::class);
    Route::get('opensurvey/detail/{id}',[App\Http\Controllers\Admin\OpensurveyController::class, 'detail']);
    Route::put('opensurvey/detail/{id}',[App\Http\Controllers\Admin\OpensurveyController::class, 'ubahblok']);
    Route::post('opensurvey/detail',[App\Http\Controllers\Admin\OpensurveyController::class, 'simpanblok']);
    Route::post('opensurvey/pertanyaan',[App\Http\Controllers\Admin\OpensurveyController::class, 'simpanpertanyaan']);
    Route::delete('opensurvey/detail/{id}',[App\Http\Controllers\Admin\OpensurveyController::class, 'hapusblok']);
    Route::get('opensurvey/detail/table/{id_survey_blok}',[App\Http\Controllers\Admin\OpensurveyController::class, 'api_pertanyaan']);
    Route::get('opensurvey/detail/get/{id_survey_blok}',[App\Http\Controllers\Admin\OpensurveyController::class, 'get_pertanyaan']);
});

Route::group(['prefix' => 'admin','as'=>'admin.','middleware' =>['auth:sanctum', 'verified']],
function(){
    Route::resource('pengguna',PenggunaController::class);

});

// Route::get('/dashboard/pengguna', 'App\Http\Controllers\Admin\PenggunaController@index');
// Route::get('/dashboard/{name}/edit', 'App\Http\Controllers\Admin\PenggunaController@edit');
// Route::put('/dashboard/{name}', 'App\Http\Controllers\Admin\PenggunaController@update');
// Route::delete('/dashboard/{name}', 'App\Http\Controllers\Admin\PenggunaController@delete');

resources/views/includes/fixedplugin.blade.php
<div class="dropdown show-dropdown">
    <a href="#" data-toggle="dropdown">
        <i class="fa fa-cog fa-2x"> </i>
    </a>
    <ul class="dropdown-menu">
        <li class="header-title"> Sidebar Filters</li>
        <li class="adjustments-line">
            <a href="javascript:void(0)" class="switch-trigger active-color">
                <div class="badge-colors text-center">
                    <span class="badge filter badge-purple" data-color="purple"></span>
                    <span class="badge filter badge-blue" data-color="blue"></span>
                    <span class="badge filter badge-green" data-color="green"></span>
                    <span class="badge filter badge-orange" data-color="orange"></span>
                    <span class="badge filter badge-red" data-color="red"></span>
                    <span class="badge filter badge-rose active" data-color="rose"></span>
                </div>
                <div class="clearfix"></div>
            </a>
        </li>
        <li class="header-title">Sidebar Background</li>
        <li class="adjustments-line">
            <a href="javascript:void(0)" class="switch-trigger background-color">
                <div class="text-center">
                    <span class="badge filter badge-white" data-color="white"></span>
                    <span class="badge filter badge-black active" data-color="black"></span>
                </div>
                <div class="clearfix"></div>
            </a>
        </li>
        <li class="adjustments-line">
            <a href="javascript:void(0)" class="switch-trigger">
                <p>Sidebar Mini</p>
                <div class="togglebutton switch-sidebar-mini">
                    <label>
                        <input type="checkbox" unchecked="">
                    </label>
                </div>
                <div class="clearfix"></div>
            </a>
        </li>
        <li class="adjustments-line">
            <a href="javascript:void(0)" class="switch-trigger">
                <p>Sidebar Image</p>
                <div class="togglebutton switch-sidebar-image">
                    <label>
                        <input type="checkbox" checked="">
                    </label>
                </div>
                <div class="clearfix"></div>
            </a>
        </li>
        <li class="header-title">Images</li>
        <li class="active">
            <a class="img-holder switch-trigger" href="javascript:void(0)">
                <img src="../assets/img/sidebar-1.jpg" alt="" />
            </a>
        </li>
        <li>
            <a class="img-holder switch-trigger" href="javascript:void(0)">
                <img src="../assets/img/sidebar-2.jpg" alt="" />
            </a>
        </li>
        <li>
            <a class="img-holder switch-trigger" href="javascript:void(0)">
                <img src="../assets/img/sidebar-3.jpg" alt="" />
            </a>
        </li>
        <li>
            <a class="img-holder switch-trigger" href="javascript:void(0)">
                <img src="../assets/img/sidebar-4.jpg" alt="" />
            </a>
        </li>
        <li class="button-container">
            <div class="">
                <a href="http://www.creative-tim.com/product/material-dashboard-pro" target="_blank" class="btn btn-rose btn-block">Buy Now</a>
            </div>
            <div class="">
                <a href="http://www.creative-tim.com/product/material-dashboard" target="_blank" class="btn btn-info btn-block">Get Free Demo</a>
            </div>
        </li>
        <li class="header-title">Thank you for 95 shares!</li>
        <li class="button-container">
            <button id="twitter" class="btn btn-social btn-twitter btn-round"><i class="fa fa-twitter"></i> &middot; 45</button>
            <button id="facebook" class="btn btn-social btn-facebook btn-round"><i class="fa fa-facebook-square"> &middot;</i>50</button>
        </li>
    </ul>
</div>

resources/views/includes/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <nav class="pull-left">
            {{-- <ul>
                <li>
                    <a href="#">
                        Home
                    </a>
                </li>
                <li>
                    <a href="#">
                        Company
                    </a>
                </li>
                <li>
                    <a href="#">
                        Portfolio
                    </a>
                </li>
                <li>
                    <a href="#">
                        Blog
                    </a>
                </li>
            </ul> --}}
        </nav>
        <p class="copyright pull-right">
            &copy;
            <script>
                document.write(new Date().getFullYear())
            </script>
            <a href="https://www.instagram.com/the_a_team_kejaksaan_ri/">The A Team</a>, Kejaksaan RI
        </p>
    </div>
</footer>

resources/views/includes/meta.blade.php
<meta charset="utf-8" />
<link rel="apple-touch-icon" sizes="76x76" href="{{ url('https://www.kejaksaan.go.id/images/logo-kejak.png') }}" />
<link rel="icon" type="image/png" href="{{ url('https://www.kejaksaan.go.id/images/logo-kejak.png') }}" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
<meta name="viewport" content="width=device-width" />
<meta name="keywords" content="E-SURVEY KEJAKSAAN">
<meta name="description" content="E-SURVEY KEJAKSAAN">
<!-- Schema.org markup for Google+ -->
<meta itemprop="name" content="E-SURVEY KEJAKSAAN">
<meta itemprop="description" content="E-SURVEY KEJAKSAAN">
<meta itemprop="image" content="../../../s3.amazonaws.com/creativetim_bucket/products/51/opt_mdp_thumbnail.jpg">

resources/views/includes/script.blade.php
<!--   Core JS Files   -->
<script src="{{ asset('/assets/js/jquery-3.1.1.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/js/jquery-ui.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/js/bootstrap.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/js/material.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/assets/js/perfect-scrollbar.jquery.min.js') }}" type="text/javascript"></script>
<!-- Forms Validations Plugin -->
<script src="{{ asset('/assets/js/jquery.validate.min.js') }}"></script>
<!--  Plugin for Date Time Picker and Full Calendar Plugin-->
<script src="{{ asset('/assets/js/moment.min.js') }}"></script>
<!--  Charts Plugin -->
<script src="{{ asset('/assets/js/chartist.min.js') }}"></script>
<!--  Plugin for the Wizard -->
<script src="{{ asset('/assets/js/jquery.bootstrap-wizard.js') }}"></script>
<!--  Notifications Plugin    -->
<script src="{{ asset('/assets/js/bootstrap-notify.js') }}"></script>
<!--   Sharrre Library    -->
<script src="{{ asset('/assets/js/jquery.sharrre.js') }}"></script>
<!-- DateTimePicker Plugin -->
<script src="{{ asset('/assets/js/bootstrap-datetimepicker.js') }}"></script>
<!-- Vector Map plugin -->
<script src="{{ asset('/assets/js/jquery-jvectormap.js') }}"></script>
<!-- Sliders Plugin -->
<script src="{{ asset('/assets/js/nouislider.min.js') }}"></script>
<!--  Google Maps Plugin    -->
<!--<script src="../assets/js/jquery.select-bootstrap.js"></script>-->
<!-- Select Plugin -->
<script src="{{ asset('/assets/js/jquery.select-bootstrap.js') }}"></script>
<!--  DataTables.net Plugin    -->
<script src="{{ asset('/assets/js/jquery.datatables.js') }}"></script>
<!-- Sweet Alert 2 plugin -->
<script src="{{ asset('/assets/js/sweetalert2.js') }}"></script>
<!--	Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
<script src="{{ asset('/assets/js/jasny-bootstrap.min.js') }}"></script>
<!--  Full Calendar Plugin    -->
<script src="{{ asset('/assets/js/fullcalendar.min.js') }}"></script>
<!-- TagsInput Plugin -->
<script src="{{ asset('/assets/js/jquery.tagsinput.js') }}"></script>
<!-- Material Dashboard javascript methods -->
<script src="{{ asset('/assets/js/material-dashboard.js') }}"></script>
<!-- Material Dashboard DEMO methods, don't include it in your project! -->
<script src="{{ asset('/assets/js/demo.js') }}"></script>
{{-- <script type="text/javascript">
    $(document).ready(function() {

        // Javascript method's body can be found in assets/js/demos.js
        demo.initDashboardPageCharts();

        demo.initVectorMap();
    });
</script> --}}

resources/views/includes/sidebar.blade.php
<div class="sidebar" data-active-color="rose" data-background-color="black" data-image=".{{ asset('/assets/img/sidebar-1.jpg') }}">
    <p hidden>{{ $user = Auth::user(); }}<p>
    <div class="logo">
        
        <a href="http://www.creative-tim.com/" class="simple-text">
            E-SURVEY
        </a>
    </div>
    <div class="logo logo-mini">
        <a href="http://www.creative-tim.com/" class="simple-text">
            E-S
        </a>
    </div>
    <div class="sidebar-wrapper">
        <div class="user">
            <div class="photo">
                <img src="{{ asset('/assets/img/faces/avatar.jpg') }}" />
            </div>
            <div class="info">
                <a data-toggle="collapse" href="#collapseExample" class="collapsed">
                    {{ $user->name }}
                    <b class="caret"></b>
                </a>
                <div class="collapse" id="collapseExample">
                    <ul class="nav">
                        <li>
                            <a href="{{ route('admin.pengguna.show', $user->id) }}">My Profile</a>
                        </li>
                        <li>
                            <a href="{{ route('admin.pengguna.edit', $user->id) }}">Edit Profile</a>
                        </li>
                        
                        <li>
                            <form method="POST" action="{{ route('logout') }}">
                                @csrf

                                <x-jet-dropdown-link href="{{ route('logout') }}"
                                         onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                    {{ __('Log Out') }}
                                </x-jet-dropdown-link>
                            </form>
                        </li>

                        
                    </ul>
                </div>
            </div>
        </div>
        
        @if ($user->roles == 'satker')
        <ul class="nav">
            <li class="">

                <a href="{{route('dashboard')}}">
                <a href="/dashboard">
                    <i class="material-icons">dashboard</i>
                    <p>Dashboard</p>
                </a>
            </li>
            <li>
                <a data-toggle="collapse" href="#survey">
                    <i class="material-icons">report</i>
                    <p>Buku Tamu
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse" id="survey">
                    <ul class="nav">
                        <li>
                            <a href="{{ url('/admin/hasilsurveypersonal', $user->satker_id) }}">Hasil Survey </a>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>  
        @else
        <ul class="nav">
            <li class="">
                <a href="/dashboard">
                    <i class="material-icons">dashboard</i>
                    <p>Dashboard</p>
                </a>
            </li>
            <li>
                <a data-toggle="collapse" href="#survey">
                    <i class="material-icons">book</i>
                    <p>Buku Tamu
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse" id="survey">
                    <ul class="nav">
                        <li>
                            <a href="{{ url('/admin/hasilsurvey') }}">Hasil Survey Keseluruhan</a>
                        </li>
                        <li>
                            <a href="{{ url('/admin/hasilsurveysatker') }}">Hasil Survey Per-Satker</a>
                        </li>
                    </ul>
                </div>
            </li>
            <li>
                <a data-toggle="collapse" href="#opensurvey">
                    <i class="material-icons">public</i>
                    <p>Open Survey
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse" id="opensurvey">
                    <ul class="nav">
                        <li>
                            <a href="{{ url('/admin/opensurvey') }}">Pengaturan Open Survey</a>
                        </li>
                    </ul>
                </div>
            </li>
            <li>
                <a data-toggle="collapse" href="#referensi">
                    <i class="material-icons">apps</i>
                    <p>Referensi
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse" id="referensi">
                    <ul class="nav">
                        <li>
                            <a href="{{ route('admin.pertanyaan.index') }}">Pertanyaan</a>
                        </li>
                    </ul>
                    <ul class="nav">
                        <li>
                            <a href="{{ route('admin.satker.index') }}">Satker</a>
                        </li>
                    </ul>
                </div>
            </li>
            <li>
                <a data-toggle="collapse" href="#pengaturan">
                    <i class="material-icons">settings</i>
                    <p>Pengaturan 
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse" id="pengaturan">
                    <ul class="nav">
                        <li>
                            <a href="{{ route('admin.pengguna.index') }}">Pengguna</a>
                        </li>
                    </ul>
                </div>
            </li>

        </ul>
        @endif
    </div>
</div>

resources/views/includes/style.blade.php
<!-- Bootstrap core CSS     -->
<link href="{{ asset('/assets/css/bootstrap.min.css') }}" rel="stylesheet" />
<!--  Material Dashboard CSS    -->
<link href="{{ asset('/assets/css/material-dashboard.css') }}" rel="stylesheet" />
<!--  CSS for Demo Purpose, don't include it in your project     -->
<link href="{{ asset('/assets/css/demo.css') }}" rel="stylesheet" />
<!--     Fonts and icons     -->
<link href="{{ asset('/assets/css/font-awesome.css') }}" rel="stylesheet" />
<link href="{{ asset('/assets/css/google-roboto-300-700.css') }}" rel="stylesheet" />

resources/views/includes/topbar.blade.php
<nav class="navbar navbar-transparent navbar-absolute">
    <div class="container-fluid">
        <div class="navbar-minimize">
            <button id="minimizeSidebar" class="btn btn-round btn-white btn-fill btn-just-icon">
                <i class="material-icons visible-on-sidebar-regular">more_vert</i>
                <i class="material-icons visible-on-sidebar-mini">view_list</i>
            </button>
        </div>
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">@yield('breadcrumb')</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="material-icons">dashboard</i>
                        <p class="hidden-lg hidden-md">Dashboard</p>
                    </a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="material-icons">notifications</i>
                        <span class="notification">5</span>
                        <p class="hidden-lg hidden-md">
                            Notifications
                            <b class="caret"></b>
                        </p>
                    </a>
                    {{-- <ul class="dropdown-menu">
                        <li>
                            <a href="#">Mike John responded to your email</a>
                        </li>
                        <li>
                            <a href="#">You have 5 new tasks</a>
                        </li>
                        <li>
                            <a href="#">You're now friend with Andrew</a>
                        </li>
                        <li>
                            <a href="#">Another Notification</a>
                        </li>
                        <li>
                            <a href="#">Another One</a>
                        </li>
                    </ul> --}}
                </li>
                {{-- <li>
                    <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="material-icons">person</i>
                        <p class="hidden-lg hidden-md">Profile</p>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <form method="POST" action="{{ route('logout') }}">
                                @csrf

                                <x-jet-dropdown-link href="{{ route('logout') }}"
                                         onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                    {{ __('Log Out') }}
                                </x-jet-dropdown-link>
                            </form>
                        </li>
                        
                    </ul>
                </li> --}}
                <li class="separator hidden-lg hidden-md"></li>
            </ul>
            <form class="navbar-form navbar-right" role="search">
                <div class="form-group form-search is-empty">
                    <input type="text" class="form-control" placeholder="Search">
                    <span class="material-input"></span>
                </div>
                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                    <i class="material-icons">search</i>
                    <div class="ripple-container"></div>
                </button>
            </form>
        </div>
    </div>
</nav>